services:
  mongo:
    env_file:
      - .env
    container_name: "mongo"
    image: mongo:7.0-rc-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./docker_volumes/mongo:/data/db
    healthcheck:
      test: sh -c "echo 'db.stats().ok'"
      interval: 3s
      timeout: 2s
      retries: 3
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - custom
  app:
    env_file:
      - .env
    environment:
      MONGO_URL: mongo
    container_name: app
    image: teleapp
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 depends.py && python3 main.py"
    ports:
      - 8000:8000
    networks:
      - custom
networks:
  custom:
    driver: bridge
